{
 "title": "Umee Oracle",
 "tags": [
  "blockchain",
  "umee"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Oracle configuration",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slash_window", "legendFormat": "{{__name__}}" },
    { "expr": "minvalidperwindow", "legendFormat": "{{__name__}}" },
    { "expr": "slash_fraction", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Next windows start",
   "type": "stat",
   "description": "Next estimated new windows start",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "next_window_start * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last block vote",
   "type": "stat",
   "description": "should go up by 5 every 30s",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_block_vote", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Window progress",
   "type": "stat",
   "description": "current slash window progress, block number in the current window",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "window_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "current window progress",
   "type": "stat",
   "description": "Percentage completion of current window",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "window_progress / slash_window", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "miss counter",
   "type": "stat",
   "description": "number of block vote was missed",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miss_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Miss Rate",
   "type": "stat",
   "description": "good when below 5%",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miss_rate", "legendFormat": "__auto" }
   ]
  }
 ]
}