{
 "title": "Umee Oracle",
 "tags": [
  "blockchain",
  "umee"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Miss Counter Stats (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "delta(miss_counter[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Miss Rate Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "miss_rate * 100", "legendFormat": "{{valoper}}" }
   ]
  },
  {
   "title": "Oracle Configuration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slash_window", "legendFormat": "slash window" },
    { "expr": "vote_period", "legendFormat": "vote period" },
    { "expr": "window_size", "legendFormat": "window size" },
    { "expr": "min_valid_per_window", "legendFormat": "minimum valid per window" },
    { "expr": "slash_fraction", "legendFormat": "slash fraction" },
    { "expr": "symbols_count", "legendFormat": "symbols count" }
   ]
  },
  {
   "title": "Window Progress",
   "type": "stat",
   "description": "current slash window progress, block number in the current window",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "window_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Window Progress",
   "type": "stat",
   "description": "Percentage completion of current window",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "window_progress / window_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Next Windows Start",
   "type": "stat",
   "description": "Next estimated new windows start",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "next_window_start", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Miss Counter",
   "type": "stat",
   "description": "number of block vote was missed",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miss_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Miss Rate",
   "type": "stat",
   "description": "good when below 5%",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "miss_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Block Vote",
   "type": "stat",
   "description": "should go up by 5 every 30s",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_block_vote", "legendFormat": "__auto" }
   ]
  }
 ]
}