groups:
  - name: umee-oracle
    rules:
      - alert: BadMissRate
        expr: miss_rate > 0.025
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "miss rate hit 2.5%"
          description: "Miss rate hit 2.5%, fix urgently {{ $labels.instance }} before it hits 5%"

      - alert: MissRateGoingUp
        expr: delta(miss_rate[5m]) > 0 and miss_rate > 0.025
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "miss rate is going up"
          description: "Miss rate is going up, check {{ $labels.instance }}"

      - alert: PriceFeederIsDown
        expr: delta(last_block_vote[5m]) < 40
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "oracle is down"
          description: "Last vote block hasn't changed for last 5m, check {{ $labels.instance }}"

      - alert: MissCounterGoingUp
        expr: delta(miss_counter[5m]) > 7
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "miss counter is going up"
          description: "One or more asset missed their vote, please check"